#!/usr/bin/env python

import sys
from pathlib import Path

import argh
import requests
from argh.decorators import named

from yunorunner.config import Config

CONFIG = Config(Path("config.toml"))
ADMIN_TOKEN = Path(".admin_token").read_text().strip()

DOMAIN = f"localhost:{CONFIG.server.port}"


def request_api(
    path: str,
    domain: str,
    verb: str,
    data: dict | None = None,
    check_return_code: bool = True,
) -> requests.Response:
    assert verb in ("get", "post", "put", "delete")
    data = {} if data is None else data

    https = False
    if domain.split(":", maxsplit=1)[0] not in ("localhost", "127.0.0.1", "0.0.0.0"):
        https = True

    proto = "https" if https else "http"
    url = f"{proto}://{domain}/api/{path}"
    headers = {"X-Token": ADMIN_TOKEN}
    response = requests.request(verb, url, headers=headers, json=data)

    if response.status_code == 403:
        print(f"Error: access refused because '{response.json()['status']}'")
        sys.exit(1)

    if check_return_code:
        # TODO: real error message
        assert response.status_code == 200, response.content

    return response


def shell() -> None:
    import ipdb  # type: ignore  # noqa: PLC0415

    ipdb.set_trace()


def add(name: str, url_or_path: str, domain: str = DOMAIN) -> None:
    request_api(
        path="job",
        verb="post",
        domain=domain,
        data={
            "name": name,
            "url_or_path": url_or_path,
        },
    )


@named("list")
def list_(all_: bool = False, domain: str = DOMAIN) -> None:
    response = request_api(
        path="job",
        verb="get",
        domain=domain,
        data={
            "all": all_,
        },
    )

    for i in response.json():
        print(f"{i['id']:4d} - {i['name']} [{i['state']}]")


def app_list(all_: bool = False, domain: str = DOMAIN) -> None:
    response = request_api(
        path="app",
        verb="get",
        domain=domain,
    )

    for i in response.json():
        print(f"{i['name']} - {i['url']}")


def delete(job_id: str, domain: str = DOMAIN) -> None:
    response = request_api(
        path=f"job/{job_id}", verb="delete", domain=domain, check_return_code=False
    )

    if response.status_code == 404:
        print(f"Error: no job with the id '{job_id}'")
        sys.exit(1)

    assert response.status_code == 200, response.content


def stop(job_id: str, domain: str = DOMAIN) -> None:
    response = request_api(
        path=f"job/{job_id}/stop", verb="post", domain=domain, check_return_code=False
    )

    if response.status_code == 404:
        print(f"Error: no job with the id '{job_id}'")
        sys.exit(1)

    assert response.status_code == 200, response.content


def restart(job_id: str, domain: str = DOMAIN) -> None:
    response = request_api(
        path=f"job/{job_id}/restart",
        verb="post",
        domain=domain,
        check_return_code=False,
    )

    if response.status_code == 404:
        print(f"Error: no job with the id '{job_id}'")
        sys.exit(1)

    assert response.status_code == 200, response.content


if __name__ == "__main__":
    argh.dispatch_commands([add, list_, delete, stop, restart, app_list, shell])
